export { RolesListComponent } from './roles/roles-list/roles-list.component';
export { RolesAddComponent } from './roles/roles-add/roles-add.component';
export { LoginComponent } from './login/login.component';
export { LeftMenuComponent } from './left-menu/left-menu.component';
export { HeaderComponent } from './header/header.component';
export { LoginHeaderComponent } from './login-header/login-header.component';
export { LoginFooterComponent } from './login-footer/login-footer.component';
export { FooterComponent } from './footer/footer.component';
export { DashboardComponent } from './dashboard/dashboard.component';
export { PageSizeRenderComponent } from './common/page-size-render/page-size-render.component';
export { PaginationRenderComponent } from './common/pagination-render/pagination-render.component';
export { SearchRenderComponent } from './common/search-render/search-render.component';
export { ConfirmDialogComponent } from './common/confirm-dialog/confirm-dialog.component';
export { DeleteDialogComponent } from './common/delete-dialog/delete-dialog.component';
export { ResetpasswordComponent } from './resetpassword/resetpassword.component';
export { ExtendMeetingComponent } from './common/extend-meeting/extend-meeting.component';
export { SettingsComponent } from './settings/settings.component';
export { FlashMessageComponent } from './flash-message/flash-message.component';
export { UserListComponent } from './user/user-list/user-list.component';
export { UserAddComponent } from './user/user-add/user-add.component';
export { MyProfileComponent } from './my-profile/my-profile.component';
export { ChangePasswordComponent } from './change-password/change-password.component';
export { HomeComponent } from './home/home.component';
export { MessageDialogComponent} from './common/message-dialog/message-dialog.component'
// export { SitelayoutComponent } from './sitelayout/sitelayout.component';
//export { BreadcrumbComponent } from './breadcrumb/breadcrumb.component';
export {CallbackComponent } from './callback/callback.component';


export { AdminLoginComponent } from './admin/admin-login/admin-login.component';
export { AdminDashboardComponent } from './admin/admin-dashboard/admin-dashboard.component';
export { SubscribersListComponent } from './admin/subscribers/subscribers-list.component';
export { HardwareListComponent } from './admin/hardware-kit/hardware-kit-list/hardware-kit-list.component';
export { HardwareAddComponent } from './admin/hardware-kit/hardware-kit-add/hardware-kit-add.component';
export { UserAdminListComponent } from './admin/admin-user/admin-user-list/admin-user-list.component';
export { AdminUserAddComponent } from './admin/admin-user/admin-user-add/admin-user-add.component';
export { SubscriberDetailComponent } from './admin/subscribers/subscriber-detail/subscriber-detail.component';
export { BulkuploadAddComponent } from './admin/bulk-upload/bulk-upload-add/bulk-upload-add.component';
export { RegisterComponent } from './subscribe/register/register.component';
export { PurchasePlanComponent } from './subscribe/purchase-plan/purchase-plan.component';
export { PaymentComponent } from './subscribe/payment/payment.component';
export { AlertsComponent } from './alerts/alerts.component';
export { LocationsListComponent } from '../components/locations/locations-list/locations-list.component';
export { AddLocationComponent } from '../components/locations/add-location/add-location.component';
export { LocationDetailsComponent } from '../components/locations/location-details/location-details.component';
export { RefrigeratorsListComponent } from '../components/refrigerators/refrigerators-list/refrigerators-list.component';
export { AddRefrigeratorComponent } from '../components/refrigerators/add-refrigerator/add-refrigerator.component';
export { RefrigeratorDashboardComponent } from '../components/refrigerators/refrigerator-dashboard/refrigerator-dashboard.component';
export { MaintenanceListComponent } from '../components/maintenance/maintenance-list/maintenance-list.component';
export { ScheduleMaintenanceComponent } from '../components/maintenance/schedule-maintenance/schedule-maintenance.component';

/*Dynamic Dashboard Start*/
export { DynamicDashboardComponent } from './dynamic-dashboard/dynamic-dashboard/dynamic-dashboard.component';
export { WidgetCounterAComponent } from './dynamic-dashboard/child-components/widget-counter-a/widget-counter-a.component';
export { WidgetCounterBComponent } from './dynamic-dashboard/child-components/widget-counter-b/widget-counter-b.component';
export { WidgetCounterCComponent } from './dynamic-dashboard/child-components/widget-counter-c/widget-counter-c.component';
export { WidgetCounterDComponent } from './dynamic-dashboard/child-components/widget-counter-d/widget-counter-d.component';
export { WidgetCounterEComponent } from './dynamic-dashboard/child-components/widget-counter-e/widget-counter-e.component';
export { WidgetCounterFComponent } from './dynamic-dashboard/child-components/widget-counter-f/widget-counter-f.component';
export { WidgetMapAComponent } from './dynamic-dashboard/child-components/widget-map-a/widget-map-a.component';
export { WidgetAlertAComponent } from './dynamic-dashboard/child-components/widget-alert-a/widget-alert-a.component';
export { WidgetupcomingmaintainceAComponent } from './dynamic-dashboard/child-components/widget-upcomingmaintaince-a/widget-upcomingmaintaince-a.component';
export { WidgetChartBComponent } from './dynamic-dashboard/child-components/widget-chart-b/widget-chart-b.component';
/*export { WidgetAlertAComponent } from './dynamic-dashboard/child-components/widget-alert-a/widget-alert-a.component';
export { WidgetChartAComponent } from './dynamic-dashboard/child-components/widget-chart-a/widget-chart-a.component';
export { WidgetChartBComponent } from './dynamic-dashboard/child-components/widget-chart-b/widget-chart-b.component';
export { WidgetChartCComponent } from './dynamic-dashboard/child-components/widget-chart-c/widget-chart-c.component';
export { WidgetChartDComponent } from './dynamic-dashboard/child-components/widget-chart-d/widget-chart-d.component';
export { WidgetMapAComponent } from './dynamic-dashboard/child-components/widget-map-a/widget-map-a.component';
export { WidgetUseCaseSpecificAComponent } from './dynamic-dashboard/child-components/widget-use-case-specific-a/widget-use-case-specific-a.component';
*/export { SizeDetectorComponent } from './dynamic-dashboard/size-detector/size-detector.component';
/*Dynamic Dashboard End*/